server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  add_header  X-Frame-Options "DENY" always;
  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Content-Type-Options nosniff;
  add_header Content-Security-Policy "default-src 'self'; font-src *;img-src * data:; script-src *; style-src *";

  location / {
    try_files $uri $uri/ /index.html;
  }

  gzip on;
  gzip_types text/plain application/javascript text/css application/json image/svg+xml;
}