export class CSVUtils {
    static convertArrayToCSV(objects: Record<string, any>[], keysToKeep: string[]): string {
        if (!objects.length) return '';

        const keys = Array.from(
            new Set(objects.flatMap(obj => Object.keys(obj)))
        ).filter((k) => keysToKeep.includes(k));

        const content = objects.map((obj) => {
            return Object.entries(obj)
                .filter((entry: [string, any]) => keysToKeep.includes(entry[0]))
                .flatMap((entry) => entry[1]);
        });

        const rows = [keys, ...content];

        const formattedRows = rows.map((r: any[]) => {
            return r.map((v: any) => {
                if (v instanceof Date) return `${String(v.getDate()).padStart(2, '0')}/${String(v.getMonth() + 1).padStart(2, '0')}/${v.getFullYear()}`;
                else return v;
            })
        })

        return formattedRows.map((row) => row.join(',')).join('\n');
    }

    static convertTimestampValueArrayToCSV(array: [number, number][][], keys: string[]): string {
        const rows: any[] = [keys];

        const length: number = array.reduce((acc: number, curr: [number, number][]) => {
            acc = (curr.length > acc) ? curr.length : acc;
            return acc;
        }, 0);

        for (let i = 0; i < length; i++) {
            const timestamp = array[0][i]?.[0] ?? '';
            const date = new Date(timestamp);
            const formattedDate = typeof timestamp === 'number' ?
                (
                    `${String(date.getDate()).padStart(2, '0')}/` +
                    `${String(date.getMonth() + 1).padStart(2, '0')}/` +
                    `${date.getFullYear()} ` +
                    `${String(date.getHours()).padStart(2, '0')}:` +
                    `${String(date.getMinutes()).padStart(2, '0')}`
                ) :
                '';

            const values: number[] = array.map((dataset: [number, number][]) => dataset[i]?.[1] ?? '');
            rows.push([formattedDate, ...values]);
        }
       
        return rows.map((row: any) => row.join(',')).join('\n');
    }
}



[
    {
        "name": "Genova - Pontedecimo",
        "area": "B",
        "basin": "Polcevera",
        "code": "GEPTX",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Polcevera"
    },
    {
        "name": "Marinella di Sarzana",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "MARIN",
        "district": "SP",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Sarzana",
        "underbasin": "Parmignola"
    },
    {
        "name": "Mattarana",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "MATRA",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Carrodano",
        "underbasin": "Mattaranasca"
    },
    {
        "name": "Mele",
        "area": "B",
        "basin": "fra Sansobbia e Polcevera",
        "code": "MELEE",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Mele",
        "underbasin": "Leira"
    },
    {
        "name": "Montenotte Inferiore",
        "area": "D",
        "basin": "Erro",
        "code": "MNINF",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Cairo Montenotte",
        "underbasin": "Erro"
    },
    {
        "name": "Santuario Monte Gazzo",
        "area": "B",
        "basin": "fra Sansobbia e Polcevera",
        "code": "MGAZZ",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Chiaravagna"
    },
    {
        "name": "Alpicella",
        "area": "B",
        "basin": "fra Sansobbia e Polcevera",
        "code": "ALPIC",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Varazze",
        "underbasin": "Teiro"
    },
    {
        "name": "S. Stefano d'Aveto",
        "area": "E",
        "basin": "Aveto",
        "code": "SSTAV",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Santo Stefano d'Aveto",
        "underbasin": "Aveto"
    },
    {
        "name": "Ellera - Foglietto",
        "area": "B",
        "basin": "Sansobbia",
        "code": "ELLRA",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Albisola Superiore",
        "underbasin": "Sansobbia"
    },
    {
        "name": "Torriglia",
        "area": "E",
        "basin": "Scrivia",
        "code": "TRRIG",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Torriglia",
        "underbasin": "Scrivia"
    },
    {
        "name": "Fallarosa",
        "area": "E",
        "basin": "Scrivia",
        "code": "FALLA",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Torriglia",
        "underbasin": "Scrivia"
    },
    {
        "name": "Genova - Bolzaneto",
        "area": "B",
        "basin": "Polcevera",
        "code": "GEBOL",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Polcevera"
    },
    {
        "name": "Iera",
        "area": "C+,M",
        "basin": "Magra",
        "code": "IERAA",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Bagnone",
        "underbasin": "Bagnone"
    },
    {
        "name": "Ferrania",
        "area": "D",
        "basin": "Bormida di Spigno",
        "code": "FERRA",
        "district": "SV",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Cairo Montenotte",
        "underbasin": "Bormida di Spigno"
    },
    {
        "name": "Lerca",
        "area": "B",
        "basin": "fra Sansobbia e Polcevera",
        "code": "LERCA",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Cogoleto",
        "underbasin": "Lerone"
    },
    {
        "name": "Levanto",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "LEVAN",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Levanto",
        "underbasin": "Ghiararo"
    },
    {
        "name": "La Foce - Mte Viseggi",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "LFMTV",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "La Spezia",
        "underbasin": null
    },
    {
        "name": "Tassani",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "TASNI",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Sestri Levante",
        "underbasin": "Petronio"
    },
    {
        "name": "Bagnone",
        "area": "C+,M",
        "basin": "Magra",
        "code": "BGNNE",
        "district": "MS",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Bagnone",
        "underbasin": "Bagnone"
    },
    {
        "name": "Rovegno",
        "area": "E",
        "basin": "Trebbia",
        "code": "ROVEG",
        "district": "GE",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Rovegno",
        "underbasin": "Trebbia"
    },
    {
        "name": "Triora",
        "area": "A",
        "basin": "Argentina",
        "code": "TRIOR",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Triora",
        "underbasin": "Argentina"
    },
    {
        "name": "Valleregia",
        "area": "B",
        "basin": "Polcevera",
        "code": "VREGI",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Serra Riccò",
        "underbasin": "Secca"
    },
    {
        "name": "Mazzola",
        "area": "C+,M",
        "basin": "Magra",
        "code": "MAZLA",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Fivizzano",
        "underbasin": "Aulella"
    },
    {
        "name": "Colle Belenda",
        "area": "A",
        "basin": "Nervia",
        "code": "BELEN",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Pigna",
        "underbasin": "Nervina"
    },
    {
        "name": "Bestagno",
        "area": "A",
        "basin": "Impero",
        "code": "BESTA",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Pontedassio",
        "underbasin": "Impero"
    },
    {
        "name": "Borgomaro",
        "area": "A",
        "basin": "Impero",
        "code": "BMARO",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Borgomaro",
        "underbasin": null
    },
    {
        "name": "Bolsine",
        "area": "B",
        "basin": "fra Sansobbia e Polcevera",
        "code": "BOLSN",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Varazze",
        "underbasin": "Teiro"
    },
    {
        "name": "Borzone",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "BRZON",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Borzonasca",
        "underbasin": "Sturla"
    },
    {
        "name": "Brugnato",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "BVARA",
        "district": "SP",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Brugnato",
        "underbasin": "Vara"
    },
    {
        "name": "Passo del Brattello",
        "area": "C+,M",
        "basin": "Magra",
        "code": "BRATT",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Pontremoli",
        "underbasin": "Magra"
    },
    {
        "name": "Calice Ligure - Ca Rosse",
        "area": "A",
        "basin": "fra Centa e Quiliano",
        "code": "CALGR",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Calice Ligure",
        "underbasin": "Pora"
    },
    {
        "name": "Airole",
        "area": "A",
        "basin": "Roya",
        "code": "AIROL",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Airole",
        "underbasin": "Roya"
    },
    {
        "name": "Crocetta di Orero",
        "area": "B",
        "basin": "Polcevera",
        "code": "CRORE",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Serra Riccò",
        "underbasin": "Secca"
    },
    {
        "name": "Alassio",
        "area": "A",
        "basin": "fra Impero e Centa",
        "code": "ALASS",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Alassio",
        "underbasin": null
    },
    {
        "name": "Camogli",
        "area": "B",
        "basin": "fra Bisagno ed Entella",
        "code": "CAMOG",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Camogli",
        "underbasin": null
    },
    {
        "name": "Campo Ligure",
        "area": "D",
        "basin": "Stura",
        "code": "CAMPL",
        "district": "GE",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Campo Ligure",
        "underbasin": "Stura"
    },
    {
        "name": "Casoni di Suvero",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "CASON",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Zignago",
        "underbasin": "Gravegnola"
    },
    {
        "name": "Cavi di Lavagna",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "CAVIP",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Lavagna",
        "underbasin": null
    },
    {
        "name": "Colle D'Oggia",
        "area": "A",
        "basin": "Argentina",
        "code": "CODOG",
        "district": "IM",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Montalto Carpasio",
        "underbasin": "Rio Carpasina"
    },
    {
        "name": "Corniolo",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "CRNLO",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Riomaggiore",
        "underbasin": null
    },
    {
        "name": "Pigna",
        "area": "A",
        "basin": "Nervia",
        "code": "PIGNA",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Pigna",
        "underbasin": "Nervia"
    },
    {
        "name": "Colle del Melogno",
        "area": "A",
        "basin": "fra Centa e Quiliano",
        "code": "CMELO",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Magliolo",
        "underbasin": "Maremola"
    },
    {
        "name": "Ceriana",
        "area": "A",
        "basin": "fra Nervia e Argentina",
        "code": "CERIA",
        "district": "IM",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Ceriana",
        "underbasin": "Armea"
    },
    {
        "name": "Colla Rossa",
        "area": "A",
        "basin": "Roya",
        "code": "CLROS",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Ventimiglia",
        "underbasin": "Bevera"
    },
    {
        "name": "Cipressa",
        "area": "A",
        "basin": "fra Argentina e Impero",
        "code": "CRAIN",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Cipressa",
        "underbasin": "Rio dei Marmi"
    },
    {
        "name": "Calizzano",
        "area": "D",
        "basin": "Bormida di Millesimo",
        "code": "CALIZ",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Calizzano",
        "underbasin": "Bormida di Millesimo"
    },
    {
        "name": "Fornola",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "FRNLA",
        "district": "SP",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Vezzano Ligure",
        "underbasin": "Magra"
    },
    {
        "name": "Alpe Vobbia",
        "area": "E",
        "basin": "Scrivia",
        "code": "AVOBB",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Vobbia",
        "underbasin": "Vobbia"
    },
    {
        "name": "Bargagli",
        "area": "B",
        "basin": "Bisagno",
        "code": "SALBE",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Bargagli",
        "underbasin": "Bisagno"
    },
    {
        "name": "Osiglia",
        "area": "D",
        "basin": "Bormida di Millesimo",
        "code": "OSIGL",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Osiglia",
        "underbasin": "Bormida di Millesimo"
    },
    {
        "name": "Sciarborasca",
        "area": "B",
        "basin": "fra Sansobbia e Polcevera",
        "code": "SCIAR",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Cogoleto",
        "underbasin": "Lerone"
    },
    {
        "name": "Scurtabo'",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "SCURT",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Varese Ligure",
        "underbasin": "Chinela"
    },
    {
        "name": "Giacopiane - Lago",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "GIACO",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Borzonasca",
        "underbasin": "Sturla"
    },
    {
        "name": "Sella di Gouta",
        "area": "A",
        "basin": "Nervia",
        "code": "GOUTA",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Apricale",
        "underbasin": "Nervia"
    },
    {
        "name": "Savona - Istituto Nautico",
        "area": "B",
        "basin": "Letimbro",
        "code": "INASV",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Savona",
        "underbasin": "Letimbro"
    },
    {
        "name": "La Macchia",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "LAMAC",
        "district": "SP",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Varese Ligure",
        "underbasin": "Vara"
    },
    {
        "name": "La Presa",
        "area": "B",
        "basin": "Bisagno",
        "code": "LAPRS",
        "district": "GE",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Bisagno"
    },
    {
        "name": "Montoggio",
        "area": "E",
        "basin": "Scrivia",
        "code": "MONTG",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Montoggio",
        "underbasin": "Scrivia"
    },
    {
        "name": "Castelnuovo Magra",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "CSMAG",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Castelnuovo Magra",
        "underbasin": null
    },
    {
        "name": "Dolcedo",
        "area": "A",
        "basin": "fra Argentina e Impero",
        "code": "DOLCE",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Dolcedo",
        "underbasin": "Rio Prino"
    },
    {
        "name": "Montalbano",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "MTBNO",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "La Spezia",
        "underbasin": null
    },
    {
        "name": "Ognio",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "OGNIO",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Neirone",
        "underbasin": "Lavagna"
    },
    {
        "name": "Mignanego",
        "area": "B",
        "basin": "Polcevera",
        "code": "MIGNA",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Mignanego",
        "underbasin": "Riccò"
    },
    {
        "name": "Villafranca Lunigiana",
        "area": "C+,M",
        "basin": "Magra",
        "code": "VIFRA",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Villafranca in Lunigiana",
        "underbasin": "Magra"
    },
    {
        "name": "Monte Rocchetta",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "MROCC",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Lerici",
        "underbasin": "Magra"
    },
    {
        "name": "Onzo - Ponterotto",
        "area": "A",
        "basin": "Centa",
        "code": "ONZPO",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Onzo",
        "underbasin": "Arroscia"
    },
    {
        "name": "Panesi",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "PANES",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Cogorno",
        "underbasin": "Entella"
    },
    {
        "name": "Piana Battolla - Ponte",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "PBATT",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Follo",
        "underbasin": "Vara"
    },
    {
        "name": "Sero' di Zignago",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "SZIGN",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Zignago",
        "underbasin": "Gravegnola"
    },
    {
        "name": "Comano",
        "area": "C+,M",
        "basin": "Magra",
        "code": "COMAN",
        "district": "MS",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Comano",
        "underbasin": "Taverone"
    },
    {
        "name": "Soliera",
        "area": "C+,M",
        "basin": "Magra",
        "code": "SOLIE",
        "district": "MS",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Fivizzano",
        "underbasin": "Aulella"
    },
    {
        "name": "La Spezia",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "SPZIA",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "La Spezia",
        "underbasin": null
    },
    {
        "name": "Sarzana",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "SRZAN",
        "district": "SP",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Sarzana",
        "underbasin": "Calcandola"
    },
    {
        "name": "Stella S. Giustina",
        "area": "B",
        "basin": "Sansobbia",
        "code": "SSGIU",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Stella",
        "underbasin": "Sansobbia"
    },
    {
        "name": "Torriglia - Garaventa",
        "area": "E",
        "basin": "Trebbia",
        "code": "TOGAR",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Torriglia",
        "underbasin": null
    },
    {
        "name": "Loco Carchelli",
        "area": "E",
        "basin": "Trebbia",
        "code": "LOCOC",
        "district": "GE",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Rovegno",
        "underbasin": "Trebbia"
    },
    {
        "name": "Luni - Provasco",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "LUNIS",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Castelnuovo Magra",
        "underbasin": null
    },
    {
        "name": "Urbe - Vara Sup.",
        "area": "D",
        "basin": "Orba",
        "code": "URVAS",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Urbe",
        "underbasin": "Orba"
    },
    {
        "name": "Varese Ligure",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "VALIG",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Varese Ligure",
        "underbasin": "Vara"
    },
    {
        "name": "Valzemola",
        "area": "D",
        "basin": "Bormida di Millesimo",
        "code": "VALZE",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Roccavignale",
        "underbasin": "Zemola"
    },
    {
        "name": "Valbrevenna - Gorra",
        "area": "E",
        "basin": "Scrivia",
        "code": "VBGOR",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Valbrevenna",
        "underbasin": null
    },
    {
        "name": "Sassello",
        "area": "D",
        "basin": "Erro",
        "code": "SASSL",
        "district": "SV",
        "last": 0.2,
        "max": 0.2,
        "min": 0,
        "municipality": "Sassello",
        "underbasin": "Erro"
    },
    {
        "name": "Manie",
        "area": "A",
        "basin": "fra Centa e Quiliano",
        "code": "MANIE",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Finale Ligure",
        "underbasin": "Sciusa"
    },
    {
        "name": "Prai",
        "area": "D",
        "basin": "Stura",
        "code": "PRAIC",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Campo Ligure",
        "underbasin": "Rio Masca"
    },
    {
        "name": "Pian dei Ratti",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "PRTTI",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Orero",
        "underbasin": "Sturla"
    },
    {
        "name": "Testico",
        "area": "A",
        "basin": "fra Impero e Centa",
        "code": "TESTI",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Testico",
        "underbasin": "Merula"
    },
    {
        "name": "Verdeggia",
        "area": "A",
        "basin": "Argentina",
        "code": "VERDE",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Triora",
        "underbasin": "Argentina"
    },
    {
        "name": "Sanda",
        "area": "B",
        "basin": "Sansobbia",
        "code": "SANDA",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Celle Ligure",
        "underbasin": "Basco"
    },
    {
        "name": "Santuario di Savona",
        "area": "B",
        "basin": "Letimbro",
        "code": "SANTU",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Savona",
        "underbasin": "Letimbro"
    },
    {
        "name": "Verzi Loano",
        "area": "A",
        "basin": "fra Centa e Quiliano",
        "code": "VERZI",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Loano",
        "underbasin": "Nimbalto"
    },
    {
        "name": "Vicomorasso",
        "area": "B",
        "basin": "Polcevera",
        "code": "VICOM",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Sant'Olcese",
        "underbasin": "Sardorella"
    },
    {
        "name": "Bosco di Rossano",
        "area": "C+,M",
        "basin": "Magra",
        "code": "BOROS",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Zeri",
        "underbasin": "Teglia"
    },
    {
        "name": "S. Margherita Ligure",
        "area": "C,C+,C-",
        "basin": "fra Bisagno ed Entella",
        "code": "SMARG",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Santa Margherita Ligure",
        "underbasin": "San siro"
    },
    {
        "name": "Sesta Godano",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "SEGOD",
        "district": "SP",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Sesta Godano",
        "underbasin": "Gottero"
    },
    {
        "name": "Sestri Levante - PonteSS1",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "SLPSS",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Sestri Levante",
        "underbasin": "Petronio"
    },
    {
        "name": "Tendola",
        "area": "C+,M",
        "basin": "Magra",
        "code": "TNDLA",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Fosdinovo",
        "underbasin": "Aulella"
    },
    {
        "name": "Brugneto Diga",
        "area": "E",
        "basin": "Trebbia",
        "code": "BRUGN",
        "district": "GE",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Torriglia",
        "underbasin": "Brugneto"
    },
    {
        "name": "Cabanne",
        "area": "E",
        "basin": "Aveto",
        "code": "CABAN",
        "district": "GE",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Rezzoaglio",
        "underbasin": "Aveto"
    },
    {
        "name": "Cairo Montenotte",
        "area": "D",
        "basin": "Bormida di Spigno",
        "code": "CAIRM",
        "district": "SV",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Cairo Montenotte",
        "underbasin": "Bormida di Spigno"
    },
    {
        "name": "Equi Terme",
        "area": "C+,M",
        "basin": "Magra",
        "code": "EQUIT",
        "district": "MS",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Fivizzano",
        "underbasin": "Aulella"
    },
    {
        "name": "Borgonuovo",
        "area": "A",
        "basin": "Nervia",
        "code": "BONUO",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Dolceacqua",
        "underbasin": "Nervia"
    },
    {
        "name": "Madonna delle Grazie",
        "area": "B",
        "basin": "fra Sansobbia e Polcevera",
        "code": "MADGR",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Leira"
    },
    {
        "name": "Statale",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "STALE",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Ne",
        "underbasin": "Graveglia"
    },
    {
        "name": "Alto - Madonna del lago",
        "area": "A",
        "basin": "Centa",
        "code": "ALTOM",
        "district": "CN",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Alto",
        "underbasin": "Pennavaira"
    },
    {
        "name": "Amborzasco",
        "area": "E",
        "basin": "Aveto",
        "code": "AMBOR",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Santo Stefano d'Aveto",
        "underbasin": null
    },
    {
        "name": "Murialdo",
        "area": "D",
        "basin": "Bormida di Millesimo",
        "code": "MURIA",
        "district": "SV",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Murialdo",
        "underbasin": "Bormida di Millesimo"
    },
    {
        "name": "Novegigola",
        "area": "C+,M",
        "basin": "Magra",
        "code": "NOVGA",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Tresana",
        "underbasin": "Magra"
    },
    {
        "name": "Bargone",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "BARGO",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Casarza Ligure",
        "underbasin": "Petronio"
    },
    {
        "name": "Villafranca Lunigiana",
        "area": "C+,M",
        "basin": "Magra",
        "code": "VFLUN",
        "district": "MS",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Villafranca in Lunigiana",
        "underbasin": "Magra"
    },
    {
        "name": "Castelvecchio di R. B.",
        "area": "A",
        "basin": "Centa",
        "code": "CASRB",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Castelvecchio di Rocca Barbena",
        "underbasin": "Neva"
    },
    {
        "name": "Carpe - Case Garoni",
        "area": "A",
        "basin": "fra Centa e Quiliano",
        "code": "CARPG",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Toirano",
        "underbasin": "Varatello"
    },
    {
        "name": "Carro",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "CARRO",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Carro",
        "underbasin": "Trambacco"
    },
    {
        "name": "Alpe Gorreto",
        "area": "E",
        "basin": "Trebbia",
        "code": "AGORR",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Gorreto",
        "underbasin": "Trebbia"
    },
    {
        "name": "Passo della Cisa",
        "area": "C+,M",
        "basin": "Magra",
        "code": "PACIS",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Pontremoli",
        "underbasin": "Magra"
    },
    {
        "name": "Parana",
        "area": "C+,M",
        "basin": "Magra",
        "code": "PARAN",
        "district": "MS",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Mulazzo",
        "underbasin": "Mangiola"
    },
    {
        "name": "Patigno",
        "area": "C+,M",
        "basin": "Magra",
        "code": "PATIG",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Zeri",
        "underbasin": "Magra"
    },
    {
        "name": "Colle di Cadibona",
        "area": "B",
        "basin": "Quiliano",
        "code": "CCADB",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Savona",
        "underbasin": "Quiliano"
    },
    {
        "name": "Calice al C. - Molunghi",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "CCORM",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Calice al Cornoviglio",
        "underbasin": "Usurana"
    },
    {
        "name": "Cenesi",
        "area": "A",
        "basin": "Centa",
        "code": "CENES",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Cisano sul Neva",
        "underbasin": "Neva"
    },
    {
        "name": "Mallare",
        "area": "D",
        "basin": "Bormida di Spigno",
        "code": "MLARE",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Mallare",
        "underbasin": "Bormida di Mallare"
    },
    {
        "name": "Minucciano",
        "area": "C+,M",
        "basin": "Magra",
        "code": "MINUC",
        "district": "LU",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Minucciano",
        "underbasin": "Aulella"
    },
    {
        "name": "Passo Ghimbegna",
        "area": "A",
        "basin": "fra Nervia e Argentina",
        "code": "CERPG",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Ceriana",
        "underbasin": "Armea"
    },
    {
        "name": "Genova - Centro Funzionale",
        "area": "B",
        "basin": "Bisagno",
        "code": "CFUNZ",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Bisagno"
    },
    {
        "name": "Chiavari",
        "area": "C,C+,C-",
        "basin": "fra Bisagno ed Entella",
        "code": "CHIRI",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Chiavari",
        "underbasin": "Entella"
    },
    {
        "name": "Castellari",
        "area": "A",
        "basin": "fra Centa e Quiliano",
        "code": "CLARI",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Pietra Ligure",
        "underbasin": "Maremola"
    },
    {
        "name": "Crocefieschi - Santuario",
        "area": "E",
        "basin": "Scrivia",
        "code": "CRCFI",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Crocefieschi",
        "underbasin": "Scrivia"
    },
    {
        "name": "Creto",
        "area": "B",
        "basin": "Bisagno",
        "code": "CRETO",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Montoggio",
        "underbasin": "Bisagno"
    },
    {
        "name": "Cuccarello",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "CUCCA",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Sesta Godano",
        "underbasin": "Gottero"
    },
    {
        "name": "Davagna",
        "area": "B",
        "basin": "Bisagno",
        "code": "DAVAG",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Davagna",
        "underbasin": "Bisagno"
    },
    {
        "name": "Diano Castello - Varcavello",
        "area": "A",
        "basin": "fra Impero e Centa",
        "code": "DCAVV",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Diano Castello",
        "underbasin": "Varcavello"
    },
    {
        "name": "Dego - Girini",
        "area": "D",
        "basin": "Bormida di Spigno",
        "code": "DEGIR",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Dego",
        "underbasin": null
    },
    {
        "name": "La Spezia - Fabiano",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "FABIA",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "La Spezia",
        "underbasin": null
    },
    {
        "name": "Fontana Fresca",
        "area": "B",
        "basin": "fra Bisagno ed Entella",
        "code": "FFRES",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Sori",
        "underbasin": "Sori"
    },
    {
        "name": "Fiorino",
        "area": "B",
        "basin": "fra Sansobbia e Polcevera",
        "code": "FIORI",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Cerusa"
    },
    {
        "name": "Framura",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "FRAMU",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Framura",
        "underbasin": "Castagnola"
    },
    {
        "name": "Imperia - Oss. Meteosismico",
        "area": "A",
        "basin": "fra Argentina e Impero",
        "code": "IMPER",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Imperia",
        "underbasin": "Caramagna"
    },
    {
        "name": "Albenga - Isolabella",
        "area": "A",
        "basin": "Centa",
        "code": "ISBLL",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Albenga",
        "underbasin": "Neva"
    },
    {
        "name": "Isoverde",
        "area": "B",
        "basin": "Polcevera",
        "code": "ISOVE",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Campomorone",
        "underbasin": "Verde"
    },
    {
        "name": "Lavagnola",
        "area": "B",
        "basin": "Letimbro",
        "code": "LAVAG",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Savona",
        "underbasin": "Letimbro"
    },
    {
        "name": "Genova - Fiumara",
        "area": "B",
        "basin": "Polcevera",
        "code": "GEFIU",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Polcevera"
    },
    {
        "name": "Genova - Geirato",
        "area": "B",
        "basin": "Bisagno",
        "code": "GEGEI",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Geirato"
    },
    {
        "name": "Albenga - Molino Branca",
        "area": "A",
        "basin": "Centa",
        "code": "MOBRA",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Albenga",
        "underbasin": "Centa"
    },
    {
        "name": "Genova - S.Ilario",
        "area": "B",
        "basin": "fra Bisagno ed Entella",
        "code": "STILA",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": null
    },
    {
        "name": "Genova - Pegli",
        "area": "B",
        "basin": "fra Sansobbia e Polcevera",
        "code": "GEPEG",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Varenna"
    },
    {
        "name": "Giacopiane - Diga",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "LGIAC",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Borzonasca",
        "underbasin": "Sturla"
    },
    {
        "name": "Licciana Nardi",
        "area": "C+,M",
        "basin": "Magra",
        "code": "LICCN",
        "district": "MS",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Licciana Nardi",
        "underbasin": "Taverone"
    },
    {
        "name": "Cembrano",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "CEMBR",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Maissana",
        "underbasin": "Borsa"
    },
    {
        "name": "Villafranca - Fornoli",
        "area": "C+,M",
        "basin": "Magra",
        "code": "VLFOL",
        "district": "MS",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Villafranca in Lunigiana",
        "underbasin": "Magra"
    },
    {
        "name": "Levanto - San Gottardo",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "LVTSG",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Levanto",
        "underbasin": "Ghiararo"
    },
    {
        "name": "Montagna",
        "area": "B",
        "basin": "Quiliano",
        "code": "MONTA",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Quiliano",
        "underbasin": "Danè"
    },
    {
        "name": "Montalto Ligure",
        "area": "A",
        "basin": "Argentina",
        "code": "MONTL",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Montalto Carpasio",
        "underbasin": "Argentina"
    },
    {
        "name": "Monte Pennello",
        "area": "B",
        "basin": "fra Sansobbia e Polcevera",
        "code": "MOPEN",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Leira"
    },
    {
        "name": "Monterosso",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "MROSS",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Monterosso al Mare",
        "underbasin": null
    },
    {
        "name": "Monte Cappellino",
        "area": "B",
        "basin": "Scrivia",
        "code": "MTECA",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Savignone",
        "underbasin": "Scrivia"
    },
    {
        "name": "Monte Settepani",
        "area": "D",
        "basin": "Bormida di Millesimo",
        "code": "MSETT",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Osiglia",
        "underbasin": "Bormida di Millesimo"
    },
    {
        "name": "Casale di Pignone",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "PIGNO",
        "district": "SP",
        "last": 0,
        "max": 0.4,
        "min": 0,
        "municipality": "Pignone",
        "underbasin": "Casale"
    },
    {
        "name": "Pitelli",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "PITLL",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "La Spezia",
        "underbasin": null
    },
    {
        "name": "Pontremoli - La Costa",
        "area": "C+,M",
        "basin": "Magra",
        "code": "PNTCA",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Pontremoli",
        "underbasin": "Magra"
    },
    {
        "name": "Pontremoli Depuratore",
        "area": "C+,M",
        "basin": "Magra",
        "code": "PNTRM",
        "district": "MS",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Pontremoli",
        "underbasin": "Magra"
    },
    {
        "name": "Croce Orero",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "ORERO",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Orero",
        "underbasin": "Canale di Isolona"
    },
    {
        "name": "Pornassio",
        "area": "A",
        "basin": "Centa",
        "code": "PORNA",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Pornassio",
        "underbasin": "Arroscia"
    },
    {
        "name": "Pietra Piccata",
        "area": "C+,M",
        "basin": "Magra",
        "code": "PPICC",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Pontremoli",
        "underbasin": "Teglia"
    },
    {
        "name": "Padivarma",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "PDVRM",
        "district": "SP",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Beverino",
        "underbasin": "Riccò"
    },
    {
        "name": "Piampaludo",
        "area": "D",
        "basin": "Orba",
        "code": "PIAMP",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Sassello",
        "underbasin": "Orba"
    },
    {
        "name": "Poggio Fearza",
        "area": "A",
        "basin": "Centa",
        "code": "PFEAR",
        "district": "IM",
        "last": 0.2,
        "max": 0.2,
        "min": 0,
        "municipality": "Montegrosso Pian Latte",
        "underbasin": "Arroscia"
    },
    {
        "name": "Pieve di Teco",
        "area": "A",
        "basin": "Centa",
        "code": "PTECO",
        "district": "IM",
        "last": 0,
        "max": 0.4,
        "min": 0,
        "municipality": "Pieve di Teco",
        "underbasin": "Arroscia"
    },
    {
        "name": "Passo del Turchino",
        "area": "B",
        "basin": "fra Sansobbia e Polcevera",
        "code": "PTURC",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Mele",
        "underbasin": "Leira"
    },
    {
        "name": "Passo del Cerreto",
        "area": "C+,M",
        "basin": "Magra",
        "code": "PCERR",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Fivizzano",
        "underbasin": "Aulella"
    },
    {
        "name": "Pizzeglio",
        "area": "A",
        "basin": "Nervia",
        "code": "PZGLI",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Castel Vittorio",
        "underbasin": "Bonda"
    },
    {
        "name": "Ranzo",
        "area": "A",
        "basin": "Centa",
        "code": "RANZO",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Ranzo",
        "underbasin": "Arroscia"
    },
    {
        "name": "Portovenere - Comune",
        "area": "C,C+,C-",
        "basin": "fra Entella e Magra",
        "code": "PVENE",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Portovenere",
        "underbasin": null
    },
    {
        "name": "Rapallo",
        "area": "C,C+,C-",
        "basin": "fra Bisagno ed Entella",
        "code": "RAPAL",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Rapallo",
        "underbasin": "Boate"
    },
    {
        "name": "Rocca Sigillina",
        "area": "C+,M",
        "basin": "Magra",
        "code": "RCSIG",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Filattiera",
        "underbasin": "Caprio"
    },
    {
        "name": "Reppia",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "REPPI",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Ne",
        "underbasin": "Graveglia"
    },
    {
        "name": "Ricco' del Golfo",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "RICCO",
        "district": "SP",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Riccò del Golfo di Spezia",
        "underbasin": "Riccò"
    },
    {
        "name": "Genova - Castellaccio",
        "area": "B",
        "basin": "Bisagno",
        "code": "RIGHI",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Bisagno"
    },
    {
        "name": "Premanico",
        "area": "B",
        "basin": "fra Bisagno ed Entella",
        "code": "PREMA",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Sturla"
    },
    {
        "name": "Pratomollo",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "PRMLO",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Borzonasca",
        "underbasin": "Sturla"
    },
    {
        "name": "Rocchetta Nervina",
        "area": "A",
        "basin": "Nervia",
        "code": "ROCNE",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Rocchetta Nervina",
        "underbasin": "Barbaira"
    },
    {
        "name": "Seborga",
        "area": "A",
        "basin": "fra Nervia e Argentina",
        "code": "SEBOR",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Seborga",
        "underbasin": "Sasso"
    },
    {
        "name": "Sella Giassina",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "SEGIA",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Neirone",
        "underbasin": "Neirone"
    },
    {
        "name": "S. Margherita Vara",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "SMVAR",
        "district": "SP",
        "last": 0,
        "max": 0.2,
        "min": 0,
        "municipality": "Carro",
        "underbasin": "Vara"
    },
    {
        "name": "Sanremo",
        "area": "A",
        "basin": "fra Nervia e Argentina",
        "code": "SREMO",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Sanremo",
        "underbasin": "San Francesco"
    },
    {
        "name": "Taglieto",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "TAGLT",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Varese Ligure",
        "underbasin": "Crovana"
    },
    {
        "name": "Tavarone",
        "area": "C,C+,M",
        "basin": "Magra",
        "code": "TAVRN",
        "district": "SP",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Maissana",
        "underbasin": "Torza"
    },
    {
        "name": "Turano",
        "area": "C+,M",
        "basin": "Magra",
        "code": "TURAN",
        "district": "MS",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Fivizzano",
        "underbasin": "Aulella"
    },
    {
        "name": "Viganego",
        "area": "B",
        "basin": "Bisagno",
        "code": "VIGAN",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Bargagli",
        "underbasin": "Bisagno"
    },
    {
        "name": "Ventimiglia",
        "area": "A",
        "basin": "Roya",
        "code": "XXMIG",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Ventimiglia",
        "underbasin": "Roya"
    },
    {
        "name": "Colle di Nava",
        "area": "A",
        "basin": "Centa",
        "code": "CNAVA",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Pornassio",
        "underbasin": "Arroscia"
    },
    {
        "name": "Genova - Gavette",
        "area": "B",
        "basin": "Bisagno",
        "code": "GEPCA",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Bisagno"
    },
    {
        "name": "Barbagelata",
        "area": "E",
        "basin": "Trebbia",
        "code": "BRGEL",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Lorsica",
        "underbasin": "Trebbia"
    },
    {
        "name": "Conna",
        "area": "A",
        "basin": "fra Impero e Centa",
        "code": "CONNA",
        "district": "SV",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Andora",
        "underbasin": "Merula"
    },
    {
        "name": "Monte Maure",
        "area": "A",
        "basin": "Roya",
        "code": "MMAUR",
        "district": "IM",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Ventimiglia",
        "underbasin": null
    },
    {
        "name": "Monte Portofino",
        "area": "B",
        "basin": "fra Bisagno ed Entella",
        "code": "MTPOR",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Camogli",
        "underbasin": null
    },
    {
        "name": "Rossiglione",
        "area": "D",
        "basin": "Stura",
        "code": "ROSGL",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Rossiglione",
        "underbasin": "Stura"
    },
    {
        "name": "Busalla",
        "area": "E",
        "basin": "Scrivia",
        "code": "BUSAL",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Busalla",
        "underbasin": "Scrivia"
    },
    {
        "name": "Genova - Quezzi",
        "area": "B",
        "basin": "Bisagno",
        "code": "GEQUE",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "Genova",
        "underbasin": "Fereggiano"
    },
    {
        "name": "Cichero",
        "area": "C,C+,C-",
        "basin": "Entella",
        "code": "CCHER",
        "district": "GE",
        "last": 0,
        "max": 0,
        "min": 0,
        "municipality": "San Colombano Certenoli",
        "underbasin": "Sturla"
    }
]